export const MigrationObjectType = Object.freeze({
  CUSTOM_OBJECTS: "custom_objects",
  CUSTOM_OBJECT_FIELDS: "custom_object_fields",
  CUSTOM_OBJECT_RELATIONSHIPS: "custom_object_relationships",
  GROUPS: "groups",
  OMNICHANNEL_QUEUES: "omnichannel_queues",
  TICKET_FIELDS: "ticket_fields",
  TICKET_FORMS: "ticket_forms",
  WEBHOOKS: "webhooks",
  MACROS: "macros",
  VIEWS: "views",
  TRIGGERS: "triggers",
  AUTOMATIONS: "automations",
  CUSTOM_OBJECT_TRIGGERS: "custom_object_triggers",
  ACCOUNT_ROUTING_SETTINGS: "account_routing_settings",
  CHAT_ROUTING_SETTINGS: "chat_routing_settings",
});

export const MIGRATION_OBJECT_ORDER = Object.freeze([
  MigrationObjectType.CUSTOM_OBJECTS,
  MigrationObjectType.CUSTOM_OBJECT_FIELDS,
  MigrationObjectType.CUSTOM_OBJECT_RELATIONSHIPS,
  MigrationObjectType.GROUPS,
  MigrationObjectType.OMNICHANNEL_QUEUES,
  MigrationObjectType.TICKET_FIELDS,
  MigrationObjectType.TICKET_FORMS,
  MigrationObjectType.WEBHOOKS,
  MigrationObjectType.MACROS,
  MigrationObjectType.VIEWS,
  MigrationObjectType.TRIGGERS,
  MigrationObjectType.AUTOMATIONS,
  MigrationObjectType.CUSTOM_OBJECT_TRIGGERS,
  MigrationObjectType.ACCOUNT_ROUTING_SETTINGS,
  MigrationObjectType.CHAT_ROUTING_SETTINGS,
]);

export const MIGRATION_OBJECT_LABELS = Object.freeze({
  [MigrationObjectType.CUSTOM_OBJECTS]: "Custom Objects",
  [MigrationObjectType.CUSTOM_OBJECT_FIELDS]: "Custom Object Fields",
  [MigrationObjectType.CUSTOM_OBJECT_RELATIONSHIPS]: "Custom Object Relationships",
  [MigrationObjectType.GROUPS]: "Groups",
  [MigrationObjectType.OMNICHANNEL_QUEUES]: "Omnichannel Queues",
  [MigrationObjectType.TICKET_FIELDS]: "Ticket Fields",
  [MigrationObjectType.TICKET_FORMS]: "Ticket Forms",
  [MigrationObjectType.WEBHOOKS]: "Webhooks",
  [MigrationObjectType.MACROS]: "Macros",
  [MigrationObjectType.VIEWS]: "Views",
  [MigrationObjectType.TRIGGERS]: "Ticket Triggers",
  [MigrationObjectType.AUTOMATIONS]: "Automations",
  [MigrationObjectType.CUSTOM_OBJECT_TRIGGERS]: "Custom Object Triggers",
  [MigrationObjectType.ACCOUNT_ROUTING_SETTINGS]: "Account Routing Settings",
  [MigrationObjectType.CHAT_ROUTING_SETTINGS]: "Chat Routing Settings",
});
